## makeCachmatrix creates a special list containing functions that create an inverse matrix. It contains 4 functions that
## 1. set the value of the matrix, 
## 2. get the value of the matrix, 
## 3. set the value of the inverse matrix
## 4 get the values of the inverse matrix) to create an inverse matrix
## Next CacheSolve will return the inverse matrix by:
# first checking if the inverse matrix is in cache 
# second if not in cache calculate the inverse matrix with solve function..

## defenition of function makeCacheMatrix which creates list of functions to create inverse matrix based on input matrix.

makeCacheMatrix <- function(x=matrix()) {               
        im <- NULL                                       # create empty object im 
        set <- function(y) {                            # definition function set: function assign values to matrix and NULL to inverse matrix object outside current environment. 
                x <<- y                                  
                im <<- NULL                              
        }   
        get <- function() {x}                              # definition function get:it calls matrix x
        setinverse <- function(solve) {im <<- solve}      # definition function setinverse: : function assigns values of calculated inverse if inverse is not in cache.
        getinverse <- function() {im}                      # definition function getinverse: function gets values inverse from cash.
        list ( set=set,                                   # create a list of functions defined.
               get=get,
               setinverse=setinverse,
               getinverse=getinverse)
}


## function which retreives inverse matrix from cache or calculates inverse matrix from matrix x 
## making use of the list of functions generated by makeCacheMatrix.


cacheSolve <- function(x, ...) {
        im <- x$getinverse()                     # call cached value inversematrix with getinverse-function
        if(!is.null(im)) {                       # if cached value is not empty
                message("getting cached data")   # return text
                return(im)                      # return inverse matrix and stop evaluation rest of the function 
        }
        data <- x$get()                         # if not in cash first call matrix with get function
        im <- solve(data, ...)                   # calculate inverse of matrix and store it in object im
        x$setinverse(im)                         # assigns the inverse result im to object im and stores it in cache with setinverse fuction
        im                                      # return inverse matrix 
}  
